services:
    - type: web
    name: sige-frontend
    rootDir: apps/web
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run preview
    env: node
    nodeVersion: 20.20.2
