"""init: tabelas UUID + branding

Revision ID: c35c773b6699
Revises: 65f66620877b
Create Date: 2026-09-06 13:20:15.777106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35c773b6699'
down_revision: Union[str, Sequence[str], None] = '65f66620877b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escolas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=True),
    sa.Column('id_curto', sa.String(length=10), nullable=False, comment='ESC001'),
    sa.Column('nif', sa.String(length=50), nullable=True),
    sa.Column('nivel_ensino', sa.Enum('PRIMARIO', 'I_CICLO', 'II_CICLO', 'COMPLEXO', 'MEDIO_TECNICO', 'SUPERIOR', name='nivelensino', native_enum=False), server_default='PRIMARIO', nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.Column('municipio', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('cor_primaria', sa.String(length=7), nullable=False),
    sa.Column('cor_secundaria', sa.String(length=7), nullable=False),
    sa.Column('cor_fundo', sa.String(length=7), nullable=False),
    sa.Column('tema', sa.String(length=20), nullable=False),
    sa.Column('fonte_titulo', sa.String(length=50), nullable=False),
    sa.Column('fonte_corpo', sa.String(length=50), nullable=False),
    sa.Column('estilo_card', sa.String(length=20), nullable=False),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('favicon_url', sa.Text(), nullable=True),
    sa.Column('permitir_auto_cadastro', sa.Boolean(), nullable=False),
    sa.Column('usar_modulo_propina', sa.Boolean(), nullable=False),
    sa.Column('usar_modulo_biblioteca', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escolas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escolas_id_curto'), ['id_curto'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    op.create_table('alunos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('escola_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_id'), ['id'], unique=False)

    op.create_table('professores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=True),
    sa.Column('escola_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professores_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_professores_id'), ['id'], unique=False)

    op.create_table('turmas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ano_letivo', sa.String(length=10), nullable=False),
    sa.Column('escola_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turmas_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_id'), ['id'], unique=False)

    op.create_table('usuario_escola',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('escola_id', sa.UUID(), nullable=True),
    sa.Column('nivel', sa.Enum('MINISTERIO', 'DIRECAO', 'DIRETOR', 'SUBDIRETOR_PEDAGOGICO', 'SUBDIRETOR_ADMINISTRATIVO', 'SECRETARIO', 'PROFESSOR', 'COORDENADOR_CURSO', 'COORDENADOR_CLASSE', 'ALUNO', 'ENCARREGADO', 'FUNCIONARIO', name='nivelacesso', native_enum=False), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=True),
    sa.Column('professor_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(nivel = 'MINISTERIO' AND escola_id IS NULL) OR (nivel!= 'MINISTERIO' AND escola_id IS NOT NULL)", name='ck_nivel_escola_consistencia'),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'escola_id', name='uq_usuario_escola')
    )
    with op.batch_alter_table('usuario_escola', schema=None) as batch_op:
        batch_op.create_index('ix_superadmin_unico', ['usuario_id'], unique=False, postgresql_where=sa.text('escola_id IS NULL'))
        batch_op.create_index(batch_op.f('ix_usuario_escola_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_escola', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_escola_id'))
        batch_op.drop_index('ix_superadmin_unico', postgresql_where=sa.text('escola_id IS NULL'))

    op.drop_table('usuario_escola')
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_escola_id'))

    op.drop_table('turmas')
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professores_id'))
        batch_op.drop_index(batch_op.f('ix_professores_escola_id'))

    op.drop_table('professores')
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_id'))
        batch_op.drop_index(batch_op.f('ix_alunos_escola_id'))

    op.drop_table('alunos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escolas_id_curto'))
        batch_op.drop_index(batch_op.f('ix_escolas_id'))

    op.drop_table('escolas')
    # ### end Alembic commands ###
